SELECT J.JOB_DESCRIPTION AS "Jobs on Rolling Tide and Starflight"
FROM JOB J
WHERE J.JOB_CODE IN
	(SELECT A.ASSIGN_JOB
	FROM ASSIGNMENT A
	WHERE A.PROJ_NUM IN
		(SELECT P.PROJ_NUM
		FROM PROJECT P
		WHERE P.PROJ_NAME IN ('Rolling Tide', 'Starflight')));