SELECT P.PROJ_NAME AS "Products with and Electrical Engineer"
FROM PROJECT P
WHERE P.PROJ_NUM IN
	(SELECT A.PROJ_NUM
	FROM ASSIGNMENT A
	WHERE A.ASSIGN_JOB IN
		(SELECT J.JOB_CODE
		FROM JOB J
		WHERE J.JOB_DESCRIPTION = 'Electrical Engineer'))