SELECT E.EMP_LNAME AS "Employee on Same Project as Arbough"
FROM EMPLOYEE E
WHERE E.EMP_FNAME != 'June'
AND E.EMP_LNAME != 'Arbough'
AND E.EMP_NUM IN
	(SELECT A.EMP_NUM
	FROM ASSIGNMENT A
	WHERE A.PROJ_NUM IN
		(SELECT A.PROJ_NUM
		FROM ASSIGNMENT A
		WHERE A.EMP_NUM IN 
			(SELECT E.EMP_NUM
			FROM EMPLOYEE E
			WHERE EMP_FNAME = 'June'
			AND EMP_LNAME = 'Arbough')));