SELECT P.PROJ_NAME AS "Project Name"
FROM PROJECT P
WHERE P.PROJ_NUM IN
	(SELECT A.PROJ_NUM
	FROM ASSIGNMENT A
	WHERE A.EMP_NUM IN
		(SELECT E.EMP_NUM
		FROM EMPLOYEE E
		WHERE E.EMP_FNAME = 'Angie'
		AND E.EMP_LNAME = 'Williamson'));